# =============================================================================
# SENSORS - Family Room State Synchronization
# =============================================================================
# Each sensor subscribes to a Home Assistant entity. When the entity's state
# changes, the sensor updates the matching button in lvgl.yaml so the display
# always reflects the true state of every device, even if it was changed via
# the HA app, a voice assistant, or an automation.
#
# SENSOR TYPES:
#   sensor (numeric)       - reads numbers like temperature, humidity, fan %
#   text_sensor            - reads string values like HVAC action
#   binary_sensor          - reads on/off state, updates button checked state
#   binary_sensor template - calculates a derived true/false from numeric data
#
# KEY PATTERNS:
#   trigger_on_initial_state: true  -> syncs button immediately on boot
#   checked: !lambda return x;      -> highlights button when entity is on
#   checked: !lambda return !x;     -> highlights button when entity is OFF
# =============================================================================


# =============================================================================
# NUMERIC SENSORS
# =============================================================================

sensor:

  # ---------------------------------------------------------------------------
  # Family Room Temperature
  # ---------------------------------------------------------------------------
  # Source:  sensor.family_room_temp_sensor_h5101_temperature
  # Updates: "temperatures" label in the top bar ("72°F / 45%")
  # Note:    Assumes HA is configured for Imperial (°F). If your sensor
  #          reports Celsius, change the format to "%.0f°C / %.0f%%" below.
  # ---------------------------------------------------------------------------
  - platform: homeassistant
    entity_id: sensor.family_room_temp_sensor_h5101_temperature
    id: fr_room_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%.0f°F / %.0f%%"
            args: [ 'x', 'id(fr_room_humidity).state' ]

  # ---------------------------------------------------------------------------
  # Family Room Humidity
  # ---------------------------------------------------------------------------
  # Source:  sensor.family_room_temp_sensor_h5101_humidity
  # Updates: "temperatures" label in the top bar ("72°F / 45%")
  # ---------------------------------------------------------------------------
  - platform: homeassistant
    entity_id: sensor.family_room_temp_sensor_h5101_humidity
    id: fr_room_humidity
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%.0f°F / %.0f%%"
            args: [ 'id(fr_room_temperature).state', 'x' ]

  # ---------------------------------------------------------------------------
  # Thermostat Current Temperature
  # ---------------------------------------------------------------------------
  # Source:    climate.family_room_thermostat (attribute: current_temperature)
  # Updates:   current value label + small dot arc on the thermostat page.
  #            Also recalculates the delta/mask arcs (the orange gap fill).
  # ---------------------------------------------------------------------------
  - platform: homeassistant
    entity_id: climate.family_room_thermostat
    id: fr_thermostat_current_temp
    attribute: current_temperature
    on_value:
      - lvgl.label.update:
          id: fr_therm_current_value
          text:
            format: "%.0f°F"
            args: [ 'x' ]
      - lvgl.arc.update:
          id: fr_therm_current_arc
          value: !lambda return (int)roundf(x);
      - lvgl.arc.update:
          id: fr_therm_delta_arc
          value: !lambda |-
            float cur = x;
            float tgt = cur;
            if (id(fr_thermostat_target_temp).has_state()) {
              tgt = id(fr_thermostat_target_temp).state;
            }
            return (int)roundf(cur > tgt ? cur : tgt);
      - lvgl.arc.update:
          id: fr_therm_mask_arc
          value: !lambda |-
            float cur = x;
            float tgt = cur;
            if (id(fr_thermostat_target_temp).has_state()) {
              tgt = id(fr_thermostat_target_temp).state;
            }
            return (int)roundf(cur < tgt ? cur : tgt);

  # ---------------------------------------------------------------------------
  # Thermostat Target Temperature (setpoint)
  # ---------------------------------------------------------------------------
  # Source:    climate.family_room_thermostat (attribute: temperature)
  # Updates:   target label (large center text) + track arc + draggable dot arc.
  #            Also recalculates the delta/mask arcs.
  # ---------------------------------------------------------------------------
  - platform: homeassistant
    entity_id: climate.family_room_thermostat
    id: fr_thermostat_target_temp
    attribute: temperature
    on_value:
      - lvgl.label.update:
          id: fr_therm_target_label
          text:
            format: "%.0f°F"
            args: [ 'x' ]
      - lvgl.arc.update:
          id: fr_therm_track_arc
          value: !lambda return (int)roundf(x);
      - lvgl.arc.update:
          id: fr_therm_target_arc
          value: !lambda return (int)roundf(x);
      - lvgl.arc.update:
          id: fr_therm_delta_arc
          value: !lambda |-
            float tgt = x;
            float cur = tgt;
            if (id(fr_thermostat_current_temp).has_state()) {
              cur = id(fr_thermostat_current_temp).state;
            }
            return (int)roundf(cur > tgt ? cur : tgt);
      - lvgl.arc.update:
          id: fr_therm_mask_arc
          value: !lambda |-
            float tgt = x;
            float cur = tgt;
            if (id(fr_thermostat_current_temp).has_state()) {
              cur = id(fr_thermostat_current_temp).state;
            }
            return (int)roundf(cur < tgt ? cur : tgt);

  # ---------------------------------------------------------------------------
  # Ceiling Fan Speed (percentage)
  # ---------------------------------------------------------------------------
  # Source:    fan.family_room_ceiling_fan (attribute: percentage)
  # Updates:   fr_fan_low_btn / fr_fan_med_btn / fr_fan_high_btn checked state
  #
  # Speed thresholds assume a 3-speed fan (33% / 66% / 100%).
  # If your fan uses different steps (e.g., 25/50/75/100 for 4-speed), update
  # the percentage values in both this file and in lvgl.yaml on_click actions.
  # ---------------------------------------------------------------------------
  - platform: homeassistant
    entity_id: fan.family_room_ceiling_fan
    id: fr_fan_percentage
    attribute: percentage
    on_value:
      - lvgl.widget.update:
          id: fr_fan_low_btn
          state:
            checked: !lambda return id(fr_fan_state).state && abs(x - 33.0f) <= 10.0f;
      - lvgl.widget.update:
          id: fr_fan_med_btn
          state:
            checked: !lambda return id(fr_fan_state).state && abs(x - 66.0f) <= 10.0f;
      - lvgl.widget.update:
          id: fr_fan_high_btn
          state:
            checked: !lambda return id(fr_fan_state).state && abs(x - 100.0f) <= 5.0f;


# =============================================================================
# TEXT SENSORS (String Values)
# =============================================================================

text_sensor:

  # ---------------------------------------------------------------------------
  # Thermostat HVAC Action
  # ---------------------------------------------------------------------------
  # Source:    climate.family_room_thermostat (attribute: hvac_action)
  # Updates:   fr_therm_mode_label on the thermostat page
  # Values:    heating / cooling / idle / off / fan
  # ---------------------------------------------------------------------------
  - platform: homeassistant
    entity_id: climate.family_room_thermostat
    id: fr_thermostat_hvac_action
    attribute: hvac_action
    on_value:
      - lvgl.label.update:
          id: fr_therm_mode_label
          text: !lambda |-
            if (x == "heating") return "Heating";
            if (x == "cooling") return "Cooling";
            if (x == "idle") return "Idle";
            if (x == "off") return "Off";
            if (x == "fan") return "Fan";
            return x.c_str();


# =============================================================================
# BINARY SENSORS (On/Off States)
# =============================================================================
# When a sensor is ON (true)  -> button shows as checked (orange highlight)
# When a sensor is OFF (false) -> button shows as unchecked (dark)
# =============================================================================

binary_sensor:

  # ---------------------------------------------------------------------------
  # Ceiling Lights
  # ---------------------------------------------------------------------------
  - platform: homeassistant
    id: fr_ceiling_lights_state
    entity_id: light.family_room_ceiling_lights
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: fr_ceiling_lights_btn
          state:
            checked: !lambda return x;

  # ---------------------------------------------------------------------------
  # Lamps (group)
  # ---------------------------------------------------------------------------
  - platform: homeassistant
    id: fr_lamps_state
    entity_id: light.family_room_lamps
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: fr_lamps_btn
          state:
            checked: !lambda return x;

  # ---------------------------------------------------------------------------
  # Fireplace Lights
  # ---------------------------------------------------------------------------
  - platform: homeassistant
    id: fr_fireplace_state
    entity_id: light.family_room_fireplace_lights
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: fr_fireplace_btn
          state:
            checked: !lambda return x;

  # ---------------------------------------------------------------------------
  # Ceiling Fan (on/off)
  # Also drives the "Off" button on the fan sub-page (inverted state).
  # ---------------------------------------------------------------------------
  - platform: homeassistant
    id: fr_fan_state
    entity_id: fan.family_room_ceiling_fan
    trigger_on_initial_state: true
    on_state:
      then:
        - lvgl.widget.update:
            id: fr_fan_btn
            state:
              checked: !lambda return x;
        - lvgl.widget.update:
            id: fr_fan_off_btn
            state:
              checked: !lambda return !x;

  # ---------------------------------------------------------------------------
  # LG Family Room TV
  # State is true when TV is on/playing/paused/idle; false when off/unavailable.
  # ---------------------------------------------------------------------------
  - platform: homeassistant
    id: fr_tv_state
    entity_id: media_player.lg_family_room_tv
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: fr_tv_btn
          state:
            checked: !lambda return x;

  # ---------------------------------------------------------------------------
  # Christmas Tree (smart plug light entity)
  # ---------------------------------------------------------------------------
  - platform: homeassistant
    id: fr_xmas_state
    entity_id: light.indoor_xmas_tree_plug_indoor_xmas_tree_relay
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: fr_xmas_btn
          state:
            checked: !lambda return x;

  # ---------------------------------------------------------------------------
  # Thermostat Mode (on/off state for the room page button)
  # ---------------------------------------------------------------------------
  # State is true when hvac_mode is heat/cool/heat_cool (not "off").
  # The Thermostat button on the family room page shows orange when active.
  # ---------------------------------------------------------------------------
  - platform: homeassistant
    id: fr_thermostat_state
    entity_id: climate.family_room_thermostat
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: fr_thermostat_btn
          state:
            checked: !lambda return x;
