# http://materialdesignicons.com/cdn/7.4.47/

# Define icons used
font:
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font
    size: 40
    bpp: 4
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
      "\U000F1A4C",  # mdi-lightbulb-night (lamps)
      "\U000F0141",  # mdi-chevron-left
      "\U000F0143",  # mdi-chevron-up
      "\U000F0140",  # mdi-chevron-down
      "\U000F0425",  # mdi-power
      "\U000F050F",  # mdi-thermometer
      "\U000F02DC",  # mdi-home (family room nav)
      "\U000F0502",  # mdi-television
      "\U000F1797",  # mdi-ceiling-fan
      "\U000F0238",  # mdi-fire (fireplace)
      "\U000F051A",  # mdi-pine-tree (xmas tree)
      "\U000F0210",  # mdi-fan (fan speed page)
      "\U000F07D6",  # mdi-led-strip (kitchen LEDs)
      "\U000F1051",  # mdi-led-strip-variant (cabinet LEDs)
      "\U000F034C",  # mdi-food (kitchen nav)
      "\U000F1120",  # mdi-table-chair (dining room nav)
      "\U000F0379",  # mdi-monitor (office nav)
      "\U000F081C",  # mdi-door-open (foyer nav)
      "\U000F1248",  # mdi-deck (deck nav)
      "\U000F024F",  # mdi-flower (patio nav)
      "\U000F04C3",  # mdi-speaker (media buttons)
      ]
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font_small
    size: 20
    bpp: 4
    glyphs: [
      "\U000F050F",  # mdi-thermometer
      ]

# Map icons to names
substitutions:
  lightbulb:          "\U000F0335"
  nightlight:         "\U000F1A4C"
  chevron_left:       "\U000F0141"
  chevron_up:         "\U000F0143"
  chevron_down:       "\U000F0140"
  power:              "\U000F0425"
  thermometer:        "\U000F050F"
  home:               "\U000F02DC"
  television:         "\U000F0502"
  ceiling_fan:        "\U000F1797"
  fire:               "\U000F0238"
  pine_tree:          "\U000F051A"
  fan:                "\U000F0210"
  led_strip:          "\U000F07D6"
  led_strip_variant:  "\U000F1051"
  food:               "\U000F034C"
  table_chair:        "\U000F1120"
  monitor:            "\U000F0379"
  door_open:          "\U000F081C"
  deck:               "\U000F1248"
  flower:             "\U000F024F"
  speaker:            "\U000F04C3"
